fix(db-lib): CommonDao.deleteByQuery
Decrease default chunkConcurrency from 32 to 16,
because Datastore started throwing this on bulk deletion:
Error: 10 ABORTED: too much contention on these datastore entities. please try again.

Also, allow to override `errorMode` via `opt`, while still defaulting to THROW_IMMEDIATELY.